### ISSUE TITLE
XtreemFS 1.2.0 does not compile with GCC 4.2.4

### ISSUE THREAD

**Issue by lkairies** [xtreemfs/xtreemfs#111]
_From [mdenbur...@gmail.com](https://code.google.com/u/108614789902553853187/) on January 11, 2010 12:44:13_

XtreemFS 1.2.0 does not compile on our cluster headnode. Version 1.1.0
compiles without problems. What steps will reproduce the problem? 1. download the XtreemFS 1.2.0 tarball
2. execute 'make' What is the expected output? What do you see instead? Compilation fails with:
g++ -o src/libxtreemfs/proxy.o -c -Wall -Wold-style-cast -Wunused-macros
-D_FILE_OFFSET_BITS=64 -g -D_DEBUG -fno-rtti -DYIELD_HAVE_OPENSSL
-DYIELD_HAVE_XATTR_H -I/usr/local/package/fuse-2.7.3/include
-Ishare/yieldfs/include -Ishare/yidl/include -Ishare/yield/include
-Iinclude -Ishare/google-breakpad/src src/libxtreemfs/proxy.cpp
src/libxtreemfs/proxy.cpp: In constructor `xtreemfs::Proxy<ProxyType,
InterfaceType>::Proxy(uint16_t, uint32_t, YIELD::platform::auto_Log, const
YIELD::platform::Time&, YIELD::ipc::auto_SocketAddress, uint8_t,
YIELD::ipc::auto_SocketFactory) [with ProxyType = xtreemfs::DIRProxy,
InterfaceType = org::xtreemfs::interfaces::DIRInterface]':
include/xtreemfs/dir_proxy.h:64:   instantiated from here
src/libxtreemfs/proxy.cpp:185: error: ISO C++ forbids casting between
pointer-to-function and pointer-to-object
src/libxtreemfs/proxy.cpp:186: error: ISO C++ forbids casting between
pointer-to-function and pointer-to-object
src/libxtreemfs/proxy.cpp: In constructor`xtreemfs::Proxy<ProxyType,
InterfaceType>::Proxy(uint16_t, uint32_t, YIELD::platform::auto_Log, const
YIELD::platform::Time&, YIELD::ipc::auto_SocketAddress, uint8_t,
YIELD::ipc::auto_SocketFactory) [with ProxyType = xtreemfs::MRCProxy,
InterfaceType = org::xtreemfs::interfaces::MRCInterface]':
include/xtreemfs/mrc_proxy.h:74:   instantiated from here
src/libxtreemfs/proxy.cpp:185: error: ISO C++ forbids casting between
pointer-to-function and pointer-to-object
src/libxtreemfs/proxy.cpp:186: error: ISO C++ forbids casting between
pointer-to-function and pointer-to-object
src/libxtreemfs/proxy.cpp: In constructor `xtreemfs::Proxy<ProxyType,
InterfaceType>::Proxy(uint16_t, uint32_t, YIELD::platform::auto_Log, const
YIELD::platform::Time&, YIELD::ipc::auto_SocketAddress, uint8_t,
YIELD::ipc::auto_SocketFactory) [with ProxyType = xtreemfs::OSDProxy,
InterfaceType = org::xtreemfs::interfaces::OSDInterface]':
include/xtreemfs/osd_proxy.h:68:   instantiated from here
src/libxtreemfs/proxy.cpp:185: error: ISO C++ forbids casting between
pointer-to-function and pointer-to-object
src/libxtreemfs/proxy.cpp:186: error: ISO C++ forbids casting between
pointer-to-function and pointer-to-object
include/xtreemfs/interfaces/constants.h: At global scope:
include/xtreemfs/interfaces/constants.h:17: warning:
'org::xtreemfs::interfaces::ONCRPC_SCHEME' defined but not used
include/xtreemfs/interfaces/constants.h:21: warning:
'org::xtreemfs::interfaces::REPL_UPDATE_PC_NONE' defined but not used
include/xtreemfs/interfaces/constants.h:22: warning:
'org::xtreemfs::interfaces::REPL_UPDATE_PC_RONLY' defined but not used
scons: **\* [src/libxtreemfs/proxy.o] Error 1
scons: building terminated because of errors.
make: **\* [client] Error 2

I'm using GCC 4.2.4 on a customized RedHat installation.

_Original issue: http://code.google.com/p/xtreemfs/issues/detail?id=111_
